variable "vpc_cidr_block" {}
variable "vpc_name" {}
variable "public-1a-cidr" {}
variable "public-1a-name" {}
variable "public-1c-cidr" {}
variable "public-1c-name" {}
variable "public-1d-cidr" {}
variable "public-1d-name" {}
variable "private-1a-cidr" {}
variable "private-1a-name" {}
variable "private-1c-cidr" {}
variable "private-1c-name" {}
variable "private-1d-cidr" {}
variable "private-1d-name" {}
variable "rds-subnet-group-name" {}